index:
  path: /
  # Uses default TemplateController as the renderer in the Symfony package
  # See https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: index.html.twig
