# routes.yaml
# Gareth Sears - 2493194S

# Other routes are set in annotations

index:
  path: /
  # Redirect index to the courses page
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: "course_instances"
    permanent: true
