# routes.yaml
# Gareth Sears - 2493194S

index:
  path: /
  # Redirect index to the courses page
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: "courses"
    permanent: true
