# services.yaml
# Gareth Sears - 2493194S
# Adapted from symfony default

# Parameters are here which don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
# Specifically, the monkeylearn API key
parameters:
  app.monkeylearn_api_key: "%env(MONKEYLEARN_API_KEY)%"
  app.monkeylearn_model_id: "%env(MONKEYLEARN_MODEL_ID)%"

services:
  _defaults:
    autowire: true # Automatically injects dependencies into services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $projectDirectory: '%kernel.project_dir%' # Allows dependency injection with this variable

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/*"
    exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]

  # EXPLICIT SERVICE DEFINITIONS

  # Sets FlagStudentsTask as a cron job
  App\Task\FlagStudentsTask:
    tags: ["ts.task"]

  
